markers:
   - point:
        x: -4.3172
        y: -11.9809
        z: 0
        xo: 0
        yo: 0
        zo: -0.921874
        wo: 0.38749
        v: 1
        location: HOME
        pause_time: 0
        index: 0
        audiofile: NOFILE
        sethorn: 0
        loadingrequest: 0
        avdrivemode: 0
        crabwheelheightrequest: 0
        crabwheelyawrequest: 0
        play_audio: 0
        set_left_indicator: 0
        set_right_indicator: 0
        laser_distance: 0
        no_go_zone: [0]
        goal: 0
   - point:
        x: 4.74469
        y: -24.7669
        z: 0
        xo: 0
        yo: 0
        zo: -0.00518203
        wo: 0.999987
        v: 1
        location: HOME
        pause_time: 0
        index: 1
        audiofile: NOFILE
        sethorn: 0
        loadingrequest: 0
        avdrivemode: 0
        crabwheelheightrequest: 0
        crabwheelyawrequest: 114
        play_audio: 0
        set_left_indicator: 0
        set_right_indicator: 0
        laser_distance: 0
        no_go_zone: [1,2]
        goal: 0
   - point:
        x: 12.6598
        y: -24.8506
        z: 0
        xo: 0
        yo: 0
        zo: -0.0053851
        wo: 0.999986
        v: 1
        location: LOCATION
        pause_time: 0
        index: 2
        audiofile: NOFILE
        sethorn: 0
        loadingrequest: 0
        avdrivemode: 0
        crabwheelheightrequest: 0
        crabwheelyawrequest: 0
        play_audio: 0
        set_left_indicator: 0
        set_right_indicator: 0
        laser_distance: 0
        no_go_zone: [0]
        goal: 0
polygons:
   - no go zone:
        x: 8.15614
        y: -29.4183
        z: 2.39989
        index: 1
        type: circle
        radius: 6
   - no go zone:
        x: 9.5338
        y: -17.8336
        z: 2.43318
        index: 2
        type: circle
        radius: 3
